config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :payments, only: [:new, :create]
    resources :comments, only: [:new, :create, :destroy]
    resources :ratings, only: [:new, :create]
  end

  root to: 'projects#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show, :edit, :update]

  namespace :admin do
    resources :users
    get '/invitations/new' => 'invitations#new'
    post '/invitations' => 'invitations#create'
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :user, presence: true
  validates :project, presence: true
  validates :body, presence: true, length: { minimum: 2 }

  scope :sorted_by_date, -> { order(created_at: :desc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  expose(:project)
  expose(:comments, ancestor: :project)
  expose(:comment, attributes: :comment_params)

  def create
    comment.user = current_user

    if comment.save
      redirect_to project_path(project), notice: 'Your comment was added successfully. Thank you!'
    else
      redirect_to project_path(project), alert: 'There\'s was wrong with your comment.'
    end
  end

  def destroy
    project = comment.project_id
    comment.delete
    redirect_to project_path project
  end

  private

  def comment_params
    params.require(:comment).permit(:user, :project, :body)
  end
end

app/views/comments/_comment.html.haml
%div.comment
  - author_class = comment.user == comment.project.owner ? 'owner ' : ''
  - author_class += comment.user.made_payment_for?(comment.project.id) ? 'paid' : 'did-not-pay'
  %h5{ class: 'author ' + author_class }
    = comment.user.decorate.full_name
    %i.payment-status
    = " on #{comment.created_at.strftime("%H:%M %d/%m/%Y")}"
    - if admin_signed_in?
      = link_to project_comment_path(project, comment), method: :delete, data: { confirm: "Are you sure?" } do
        %span.glyphicon.glyphicon-remove
  %p= comment.body

app/views/comments/_form.html.haml
= simple_form_for comment, url: project_comments_path(project) do |f|
  = f.input :body, label: false
  = f.button :submit, 'Add Comment'