config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :payments, only: [:new, :create]
    resources :comments, only: [:new, :create, :destroy]
    resources :ratings, only: [:new, :create]
  end

  root to: 'projects#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show, :edit, :update]

  namespace :admin do
    resources :users
    get '/invitations/new' => 'invitations#new'
    post '/invitations' => 'invitations#create'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :payments
  has_many :projects, foreign_key: :owner_id
  has_many :paid_projects, -> { uniq }, through: :payments, source: :project
  has_many :ratings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validate :cant_be_both_admin_and_inactive

  def cant_be_both_admin_and_inactive
    user_roles = roles.map(&:name)
    if user_roles.include?('admin') && user_roles.include?('inactive')
      errors.add(:roles, "User can't be both admin and inactive")
    end
  end

  %i(admin regular inactive).each do |role|
    define_method("#{role}?") do
      has_role? role
    end
  end

  def made_payment_for?(project_id)
    paid_projects.exists?(id: project_id)
  end

  def self.find_for_authentication(conditions)
    user = super
    if user
      return nil if user.inactive?
    end
    user
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    expose(:users)
    expose(:user)

    def index
      self.users = User.all.page params[:page]
    end


    def create
      user = User.new user_params
      if user.save
        flash[:notice] = "User created!"
        redirect_to admin_users_path
      else
        flash[:error] = "There were errors with creating user"
        redirect_to new_admin_user_path
      end
    end

    def update
      self.user.update user_params
      if user.save
        flash[:notice] = "User updated!"
        redirect_to admin_users_path
      else
        flash[:error] = "There were errors with updating user"
        render :edit
      end
    end

    def destroy
      user.add_role :inactive
      redirect_to admin_users_path
    end

    def new_invitation
    end

    private
    def user_params
      params.require(:user).permit(:email, :password, :first_name, :last_name, :occupation, :country, role_ids: [])
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super
    resource.add_role :regular
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  expose(:user, attributes: :user_params)

  def show
  end

  def update
    if current_user == user && user.save
      redirect_to user_path(user), notice: 'Your profile has been updated'
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/edit.html.haml
%h2 Edit your profile
=simple_form_for user do |p|
    =p.input :first_name
    =p.input :last_name
    =p.button :submit

app/views/users/show.html.haml
%table.table.table-condensed
  %tbody
    %tr
      %td= "First name:"
      %td= user.first_name
    %tr
      %td= "Last name:"
      %td= user.last_name
    %tr
      %td= "Total payments:"
      %td= number_to_currency(user.payments.sum(:value))
- if current_user?(user)
  = link_to 'Edit user', edit_user_path(user), class: 'btn btn-default'

- if user.projects.any?
  %h2 Your projects
  %table.table.table-striped
    %thead
      %tr
        %th Project name
        %th Project description
        %th Current funds
        %th Project goal
        %th Expires at
        %th Edit
    %tbody
      - user.projects.each do |p|
        %tr
          %td= p.name
          %td= p.description
          %td= number_to_currency(p.current_funds)
          %td= number_to_currency(p.goal)
          %td= p.finish_date
          - if current_user?(p.owner)
            %td= link_to 'Edit', edit_project_path(p)

- if user.paid_projects.any?
  %h2 Your contributions
  %table.table.table-striped
    %thead
      %tr
        %th Project name
        %th Description
        %th Your contribution
    %tbody
      - user.paid_projects.uniq.each do |p|
        %tr
          %td= p.name
          %td= p.description
          %td= number_to_currency(p.payments.by(user.id).sum(:value))