config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :payments, only: [:new, :create]
    resources :comments, only: [:new, :create, :destroy]
    resources :ratings, only: [:new, :create]
  end

  root to: 'projects#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show, :edit, :update]

  namespace :admin do
    resources :users
    get '/invitations/new' => 'invitations#new'
    post '/invitations' => 'invitations#create'
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :owner, class_name: "User"
  has_many :payments
  has_many :comments
  has_many :ratings

  scope :active, -> { where(status: 'active') }
  scope :inactive, -> { where.not(status: 'active') }

  validates :owner_id, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :goal, presence: true,
                   numericality: { greater_than_or_equal_to: 0 }
  validates :current_funds, presence: true,
                            numericality: { greater_than_or_equal_to: 0 }
  validates :setup_date, presence: true
  validates :finish_date, presence: true
  validate :update_date_validate, on: :update
  validate :date_validate, on: :create
  validate :goal_range

  enum status: [ :active, :succeed, :failed, :waiting ]

  def date_validate
    if setup_date.nil? || finish_date.nil?
      errors.add(:setup_date, "Dates can't be empty")
    else
      if setup_date < Date.today
        errors.add(:setup_date, "Project can't start in the past")
      elsif finish_date < setup_date
        errors.add(:finish_date, "Project can't be finished before its start")
      end
    end
  end

  def update_date_validate
    if finish_date.nil?
      errors.add(:setup_date, "Finish date can't be empty")
    else
      if finish_date < setup_date
        errors.add(:finish_date, "Project can't be finished before its start")
      elsif finish_date < Date.today
        errors.add(:finish_date, "Project can't be finished before today")
      end
    end

  end

  def goal_range
    if goal.nil?
      errors.add(:setup_date, "Goal can't be empty")
    else
      if goal > 2_147_483_647
        errors.add(:goal, "We are sorry but your goal is too big")
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  expose(:active_projects) { Project.active }
  expose(:remaining_projects)  { Project.inactive }
  expose(:projects)
  expose(:project, attributes: :projects_params)
  expose(:comments) { project.comments.sorted_by_date }


  def create
    project.owner = current_user

    if project.save
      set_project_status
      redirect_to project_path(project), notice: 'Project has been created'
    else
      render :new
    end
  end

  def edit
  end

  def show
    daily_payments = Hash.new(0)
    total_payments = Hash.new(0)
    total_funds = 0
    @project_goal = {}
    daily_payments[project.setup_date.strftime('%d %b %y')] = 0
    total_payments[project.setup_date.strftime('%d %b %y')] = 0

    project.payments.order(:created_at).map do |payment|
      daily_payments[payment.created_at.strftime('%d %b %y')] += payment.value
      total_funds += payment.value
      total_payments[payment.created_at.strftime('%d %b %y')] = total_funds
      @project_goal[payment.created_at.strftime('%d %b %y')] = project.goal
    end


    @project_goal[project.setup_date.strftime('%d %b %y')] = project.goal
    @daily_payments_labels = daily_payments.keys
    @daily_payments_values = daily_payments.values.map(&:to_i)
    @total_payments_values = total_payments.values.map(&:to_i)
    @finish_date = project.finish_date.to_s.chomp(" UTC")
  end

  def update
    if project.save
      redirect_to project_path(project), notice: 'Your project has been updated'
    else
      render :edit
    end
  end

  def index
    @finish_date = project.finish_date.to_s.chomp(" UTC")
  end

  private

  def projects_params
    params.require(:project).permit(:owner, :name, :description, :goal, :setup_date, :finish_date)
  end

  def set_project_status
    if project.setup_date == Date.today
      project.active!
    else
      project.waiting!
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
=simple_form_for project do |p|
    =p.input :name
    =p.input :description, as: :text
    =p.input :goal
    =p.input :setup_date, as: :date, start_year: Date.today.year
    =p.input :finish_date, as: :date, start_year: Date.today.year
    =p.button :submit

app/views/projects/_project.html.haml
%td= link_to project.name, project
%td= project.description
%td= project.finish_date.to_s.chomp(" UTC")
%td= number_to_currency(project.goal)
%td= number_to_currency(project.current_funds)
%td= project.decorate.percent_funds_raised
%td
  %i{ class: 'status status-' + project.status }

app/views/projects/_project_comments.html.haml
%h4= 'Comments'
- if comments.empty?
  %p= 'Be the first one to comment on this project!'
- else
  - comments.each do |comment|
    = render comment
- if user_signed_in?
  %h5= 'Add Comment'
  = render 'comments/form', comment: project.comments.new, project: project

app/views/projects/_project_payments.html.haml
%h4= 'Payments'
- if project.payments.empty?
  %p= 'Be the first one to pay for this project!'
- else
  %ul
    - project.payments.each do |payment|
      %li
        = render payment
- if user_signed_in? && project.active?
  = link_to 'Add Payment', new_project_payment_path(project), class: 'btn btn-default'

app/views/projects/_project_rating.html.haml
- if project.succeed? && user_signed_in? && project.payments.by(current_user.id).any?
  .rating
    %h4= 'Rate This Project'
    - if project.ratings.by(current_user.id).first.nil?
      = render 'ratings/form', rating: project.ratings.new, project: project
    - else
      %p
        You already rated this project:
        = project.ratings.by(current_user.id).first.value

app/views/projects/_projects_table.html.haml
- if projects.empty?
  %p= 'Currently, there are no projects here.'
- else
  %table.table
    %thead
      %tr
        %th= 'Name'
        %th= 'Description'
        %th= 'Finish Time'
        %th= 'Goal'
        %th= 'Current Funds'
        %th= '%'
        %th= 'Status'
    %tbody
      - projects.each do |project|
        %tr.project
          = render project

app/views/projects/edit.html.haml
%h1 Update your project
=simple_form_for project do |p|
    =p.input :name
    =p.input :description, as: :text
    =p.input :finish_date, as: :date, start_year: Date.today.year
    =p.button :submit

app/views/projects/index.html.haml
%h2 Active Projects
= render 'projects_table', projects: active_projects

- if user_signed_in?
  =link_to "New Project", new_project_path, class:"btn btn-primary"

%h2 Inactive Projects
= render 'projects_table', projects: remaining_projects

app/views/projects/new.html.haml
%h1 Add new project
=render 'form'

app/views/projects/show.html.haml
.row.project
  .col-xs-12
    %h2.project-name
      = project.name
      - if project.succeed?
        = " (#{ project.decorate.mean_rating }/#{Rating::MAX})"
  .details.col-md-6
    %div
      %h4= 'Description'
      %p= project.description
    %div
      %h4= 'Goal'
      %p= number_to_currency(project.goal)
    %div
      %h4= 'Currrent funds'
      %p= number_to_currency(project.current_funds)
    %div
      %h4= 'Status'
      %p
        %i{ class: 'status status-' + project.status }
      - if current_user?(project.owner)
        = link_to 'Edit Project', edit_project_path(project), class: 'btn btn-default'
    %div
      %h4= 'Time remaining'
      %div#counter
      :javascript
          $('#counter').countdown(#{@finish_date.to_json})
          .on('update.countdown', function(event) {
            var format = '%H:%M:%S';
            if(event.offset.days > 0) {
              format = '%-d day%!d ' + format;
            }
            if(event.offset.weeks > 0) {
              format = '%-w week%!w ' + format;
            }
          $(this).html(event.strftime(format));
          });

    %div
      %h4= 'Owner'
      %p= project.owner.decorate.full_name
    %canvas#canvas{:height => "300", :width => "450"}
    #placeholder
  .user-input.col-md-6
    .toggle-buttons
      = link_to 'Show Payments','#collapse', class: 'btn btn-default', id: 'payment', "data-toggle" => "collapse", "aria-expanded"=>"false", "aria-controls"=>"collapse"
      = link_to 'Show Comments','#collapse_comments', class: 'btn btn-default', id: 'comment', "data-toggle" => "collapse", "aria-expanded"=>"false", "aria-controls"=>"collapse_comments"
    = render 'project_rating'
    .payments.collapse#collapse
      = render 'project_payments'
    .comments.collapse#collapse_comments
      = render 'project_comments'

:javascript
  window.dataArray = #{raw @daily_payments_values.to_json}
  window.dataArrayAll = #{raw @total_payments_values.to_json}
  window.labelArray = #{raw @daily_payments_labels.to_json}
  window.limit = #{raw @project_goal.to_json}