config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :payments, only: [:new, :create]
    resources :comments, only: [:new, :create, :destroy]
    resources :ratings, only: [:new, :create]
  end

  root to: 'projects#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show, :edit, :update]

  namespace :admin do
    resources :users
    get '/invitations/new' => 'invitations#new'
    post '/invitations' => 'invitations#create'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :payments
  has_many :projects, foreign_key: :owner_id
  has_many :paid_projects, -> { uniq }, through: :payments, source: :project
  has_many :ratings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validate :cant_be_both_admin_and_inactive

  def cant_be_both_admin_and_inactive
    user_roles = roles.map(&:name)
    if user_roles.include?('admin') && user_roles.include?('inactive')
      errors.add(:roles, "User can't be both admin and inactive")
    end
  end

  %i(admin regular inactive).each do |role|
    define_method("#{role}?") do
      has_role? role
    end
  end

  def made_payment_for?(project_id)
    paid_projects.exists?(id: project_id)
  end

  def self.find_for_authentication(conditions)
    user = super
    if user
      return nil if user.inactive?
    end
    user
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    expose(:users)
    expose(:user)

    def index
      self.users = User.all.page params[:page]
    end


    def create
      user = User.new user_params
      if user.save
        flash[:notice] = "User created!"
        redirect_to admin_users_path
      else
        flash[:error] = "There were errors with creating user"
        redirect_to new_admin_user_path
      end
    end

    def update
      self.user.update user_params
      if user.save
        flash[:notice] = "User updated!"
        redirect_to admin_users_path
      else
        flash[:error] = "There were errors with updating user"
        render :edit
      end
    end

    def destroy
      user.add_role :inactive
      redirect_to admin_users_path
    end

    def new_invitation
    end

    private
    def user_params
      params.require(:user).permit(:email, :password, :first_name, :last_name, :occupation, :country, role_ids: [])
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super
    resource.add_role :regular
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  expose(:user, attributes: :user_params)

  def show
  end

  def update
    if current_user == user && user.save
      redirect_to user_path(user), notice: 'Your profile has been updated'
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/admin/users/edit.html.haml
.admin-user-form
  %h3 Update user
  = simple_form_for(user, url: admin_user_path(user), method: :put,  html: { class: 'form-horizontal' }) do |f|
    = f.input :email
    = f.input :first_name
    = f.input :last_name
    = f.input :occupation
    = f.input :country
    = f.association :roles,  as: :check_boxes
    = f.button :submit, class: 'btn btn-success'

app/views/admin/users/index.html.haml
%h3 Manage Users
%span.glyphicon.glyphicon-user
.create-user-links
  = link_to new_admin_user_path, class: 'btn btn-success' do
    = "Create User"
    %span.glyphicon.glyphicon-plus
  = link_to admin_invitations_new_path, class: 'btn btn-success' do
    = "Invite User"
    %span.glyphicon.glyphicon-envelope
- if users.any?
  = page_entries_info users
  %table.table
    %thead
      %tr
        %th Email
        %th Full name
        %th Occupation
        %th Country
        %th Roles
        %th Invitation status
        %th Updated at
        %th Created at
        %th Actions
    %tbody
      - users.each do |user|
        %tr
          %td= user.email
          %td= user.decorate.full_name
          %td= user.occupation
          %td= user.country
          %td= user.decorate.display_roles
          %td= user.decorate.invitation_status
          %td= user.updated_at
          %td= user.created_at
          %td
            = link_to admin_user_path(user) do
              %span.glyphicon.glyphicon-search
            = link_to edit_admin_user_path(user) do
              %span.glyphicon.glyphicon-pencil
            - unless user.inactive? or user.admin?
              = link_to admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } do
                %span.glyphicon.glyphicon-remove
  = paginate users
- else
  %h3 No users found :(

app/views/admin/users/new.html.haml
.admin-user-form
  %h3 Create new user
  = simple_form_for(user, url: admin_users_path, method: :post,  html: { class: 'form-horizontal' }) do |f|
    = f.input :email
    = f.input :password
    = f.input :first_name
    = f.input :last_name
    = f.input :occupation
    = f.input :country
    = f.association :roles,  as: :check_boxes
    = f.button :submit, class: 'btn btn-success'

app/views/admin/users/show.html.haml
%h3= user.decorate.full_name
%ul.list-group
  %li.list-group-item= "Email: " + user.email
  %li.list-group-item= "Roles: " + user.decorate.display_roles
  %li.list-group-item= "From: " + user.country
  %li.list-group-item= "Occupation: " + user.occupation
  %li.list-group-item= "Invitation status: " + user.decorate.invitation_status
  %li.list-group-item= "Last update: " + user.updated_at.to_s
  %li.list-group-item= "Created: " + user.created_at.to_s